### ISSUE TITLE
update the formats of alignments -- the URLs don't work

### ISSUE THREAD

**Issue by gregorycrane** [ChiaraPalladino/TuftsDCC#1]
for example, at https://github.com/ChiaraPalladino/TuftsDCC/wiki/Brian-Clark,-Achilles-after-Homer:-Quintus-of-Smyrna's-Posthomerica

replace URLs such as 
Brian's alignments: Spanish-English-Greek http://ugarit.ialigner.com/align.php?function=update&id=2188

with URLs in the form at:

http://ugarit.ialigner.com/text.php?id=2188

**Comment by ChiaraPalladino** [comment]
the IDs there are quite messed up, so I asked the students to provide me the exact links to their alignments. By replacing the links with the correct strings, not all the alignments point to Quintus of Smyrna.
